import Head from "next/head";
import Image from "next/image";
import About from "../components/about/about";
import Banner from "../components/banner/banner";
import Blog from "../components/blog/blog";
import Button from "../components/button/button";
import Footer from "../components/footer/footer";
import Navbar from "../components/navbar/navbar";
import NewLaunch from "../components/newLaunch/newLaunch";
import Partner from "../components/partner/partner";
import Sports from "../components/sports/sports";
import styles from "../styles/Home.module.css";

const record = [
  { name: "Outlets", number: "50+" },
  { name: "Students", number: "100k+" },
  { name: "Trainers", number: "200+" },
  { name: "Members", number: "50k+" },
];
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fitbit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>
        <Banner />
      </div>
      <Partner />
      <Sports />
      <About />
      <div className={styles.records}>
        {record.map((item, index) => (
          <div className={styles.record} key={index}>
            <h1>{item.number}</h1>
            <p>{item.name}</p>
          </div>
        ))}
      </div>
      <NewLaunch />
      <Blog />
      <div id="Pricing" className={styles.newsLetter}>
        <div className={styles.newsLetterInner}>
          <div>
            <h1>Subscribe to our</h1>
            <h1>newsletter.</h1>
          </div>
          <Button label="Subscribe" ClassNameAtt="subscribe" />
        </div>
      </div>
      <Footer />
    </div>
  );
}
